config/routes.rb
Rails.application.routes.draw do
  resources :preparatories
  resources :answers
  resources :lessons do
    resources :steps
  end

  namespace :authors do
    resources :eg_posts, :except => [:show] do
      member do
        delete :delete_image_attachment
      end
    end
  end
  resources :eg_posts, :only => [:index, :show] 

  resources :eg_users 
  get 'users/index'
  devise_for :users, path: '', path_names: {sign_in: 'login', sign_out: 'logout'}, controllers: { sessions: 'users/sessions' }
  resources :users do
    member do
      get :delete_image_attachment
    end
  end

  get 'mockups/page_a'
  get 'mockups/page_b'
  get 'mockups/bs_grid'
  get 'mockups/bs_gutter'
  get 'mockups/bs_buttons'
  get 'mockups/bs_cards_and_panels'
  get 'mockups/bs_images'
  get 'mockups/bs_icons'
  get 'mockups/bs_theming_kit'
  get 'mockups/bs_ud_home'
  get 'mockups/bs_ud_news'
  get 'mockups/bs_ud_tema'
  get 'mockups/edu_index_4'
  get 'mockups/edu_course_detail_min'
  get 'mockups/ud_lessons_index'
  get 'mockups/ud_lessons_show'
  get 'mockups/ud_lessons_steps_show'
  get 'mockups/youtube_player'
  get 'mockups/stimulus_demo'
  #get 'eg_posts', to:'eg_posts#index', as: :user_root #creates user_root_path (default path after sign_in)
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'lessons#index'
end

app/models/eg_post.rb
class EgPost < ApplicationRecord
  # == Constants ============================================================
  
  # == Extensions ===========================================================

  # == Attributes ===========================================================

  ## Active Storage
  has_one_attached :header_image
  
  ## Action Text
  has_rich_text :content

  # == Relationships ========================================================

  ## association one-to-many
  belongs_to :user

  # == Validations ==========================================================

  # == Scopes ===============================================================

  scope :published, -> { where(published: true) }

  # == Callbacks ============================================================

  # == Class Methods ========================================================

  # == Instance Methods =====================================================

  ## getter method
  def published_at_formatted 
    if published_at.present?
      ActionController::Base.helpers.l published_at, format: :my_long
    else
      ActionController::Base.helpers.t 'eg_posts.not_published'
    end
  end
end

app/controllers/authors/eg_posts_controller.rb
class Authors::EgPostsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_eg_post, only: %i[ edit update destroy ]
  #layout 'dashboard'

  # GET /authors/eg_posts or /authors/eg_posts.json
  def index
    #@eg_posts = EgPost.all
    #@eg_posts = EgPost.published.order(created_at: "DESC")
    #@pagy, @eg_posts = pagy(EgPost.all, items: 6)
    #@pagy, @eg_posts = pagy(EgPost.published.order(created_at: "DESC"), items: 2)
    @pagy, @eg_posts = pagy(EgPost.all.order(created_at: "DESC"), items: 2) if current_user.admin?
    @pagy, @eg_posts = pagy(current_user.eg_posts.order(created_at: "DESC"), items: 2) unless current_user.admin?
    #@posts = current_user.eg_posts.order(created_at: "DESC") unless current_user.admin?
    #@posts = Post.all.order(created_at: "DESC") if current_user.admin?
    authorize @eg_posts
  end

  # GET /authors/eg_posts/new
  def new
    @eg_post = EgPost.new
    authorize @eg_post
  end

  # GET /authors/eg_posts/1/edit
  def edit
  end

  # POST /authors/eg_posts or /authors/eg_posts.json
  def create
    # params restituisce una stringa ed il check-box restituisce "1" se flaggato.
    params[:eg_post][:published_at] = "#{DateTime.current}" if params[:eg_post][:published] == "1" and params[:eg_post][:published_at].blank?
    params[:eg_post][:published_at] = "" if params[:eg_post][:published] == "0"

    @eg_post = EgPost.new(eg_post_params)
    authorize @eg_post

    respond_to do |format|
      if @eg_post.save
        format.html { redirect_to eg_post_url(@eg_post), notice: "Eg post was successfully created." }
        format.json { render :show, status: :created, location: @eg_post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @eg_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /authors/eg_posts/1 or /authors/eg_posts/1.json
  def update
    #raise "published è #{params[:post][:published] == "1"} - published_at è #{params[:post][:published_at].blank?} - La data di oggi è #{DateTime.current}"
    # params restituisce una stringa ed il check-box restituisce "1" se flaggato.
    params[:eg_post][:published_at] = "#{DateTime.current}" if params[:eg_post][:published] == "1" and params[:eg_post][:published_at].blank?
    params[:eg_post][:published_at] = "" if params[:eg_post][:published] == "0"

    respond_to do |format|
      if @eg_post.update(eg_post_params)
        format.html { redirect_to eg_post_url(@eg_post), notice: "Eg post was successfully updated." }
        format.json { render :show, status: :ok, location: @eg_post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @eg_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/eg_posts/1 or /authors/eg_posts/1.json
  def destroy
    @eg_post.destroy

    respond_to do |format|
      format.html { redirect_to authors_eg_posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # GET /authors/eg_posts/1/delete_image_attachment
  def delete_image_attachment
    @image_to_delete = ActiveStorage::Attachment.find(params[:id])
    @image_to_delete.purge
    redirect_back(fallback_location: request.referer)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_eg_post
      @eg_post = EgPost.find(params[:id])
      authorize @eg_post
    end

    # Only allow a list of trusted parameters through.
    def eg_post_params
      params.require(:eg_post).permit(:meta_title, :meta_description, :headline, :incipit, :price, :header_image, :content, :published, :published_at, :user_id)
    end
end

app/controllers/eg_posts_controller.rb
class EgPostsController < ApplicationController

  # GET /eg_posts or /eg_posts.json
  def index
    #@eg_posts = EgPost.all
    #@eg_posts = EgPost.published.order(created_at: "DESC")
    #@pagy, @eg_posts = pagy(EgPost.all, items: 2)
    @pagy, @eg_posts = pagy(EgPost.published.order(created_at: "DESC"), items: 2)
    authorize @eg_posts
  end

  # GET /eg_posts/1 or /eg_posts/1.json
  def show
    @eg_post = EgPost.find(params[:id])
    authorize @eg_post
  end
end

app/helpers/eg_posts_helper.rb
module EgPostsHelper
end

app/views/authors/eg_posts/_eg_post.html.erb
<div id="<%= dom_id eg_post %>">
  <p>
    <strong>Meta title:</strong>
    <%= eg_post.meta_title %>
  </p>

  <p>
    <strong>Meta description:</strong>
    <%= eg_post.meta_description %>
  </p>

  <p>
    <strong>Headline:</strong>
    <%= eg_post.headline %>
  </p>

  <p>
    <strong>Incipit:</strong>
    <%= eg_post.incipit %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= eg_post.price %>
    <br> numero formattato: <%= number_to_currency(eg_post.price) %>
    <br> numero formattato con 3 decimali: <%= number_to_currency(eg_post.price, precision: 3) %>
    <br> numero formattato con 4 decimali: <%= number_to_currency(eg_post.price, precision: 4) %>
    <br> numero formattato con 5 decimali: <%= number_to_currency(eg_post.price, precision: 5) %>
    (nel database abbiamo dichiarato 4 decimali quindi la quinta cifra decimale sarà sempre zero)
    <br> numero formattato con frase: <%= t "number.currency.format.price_for_reports", price: number_to_currency(eg_post.price, precision: 2) %>
    <br> numero formattato descrittivo con frase: <%= t "number.currency.format.price_for_reports", price: number_to_human(eg_post.price) %>
  </p>

  <% if eg_post.header_image.attached? %>
    <p><%= image_tag eg_post.header_image %></p>
    <p><%= image_tag eg_post.header_image.variant(resize_to_limit: [100, 100]) %></p>
  <% else %>
    <p>Nessuna immagine presente</p>
  <% end %>

  <p>
    <strong>Content:</strong>
    <%= eg_post.content %>
  </p>

  <p>
    <strong>published:</strong>
    <%= eg_post.published %>
  </p>

  <p>
    <strong>published_at:</strong>
    <%= l eg_post.published_at, format: :my_long if eg_post.published_at.present? %>
    <%= eg_post.published_at_formatted %>
  </p>

  <p>
    <strong>User:</strong>
    <%= eg_post.user_id %>
  </p>

  <p>
    <strong>created_at:</strong>
    <%= l eg_post.created_at, format: :my_long %>
  </p>

  <p>
    <strong>updated_at:</strong>
    <%= l eg_post.created_at, format: :my_long %>
  </p>

</div>

app/views/authors/eg_posts/_form.html.erb
<div class="container my-2">
  <div class="row">
    <div class="col">
      <%= form_with(model: eg_post, url: authors_url) do |form| %>
        <% if eg_post.errors.any? %>
          <div style="color: red">
            <h2><%= pluralize(eg_post.errors.count, "error") %> prohibited this eg_post from being saved:</h2>

            <ul>
              <% eg_post.errors.each do |error| %>
                <li><%= error.full_message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <div>
          <%= form.label :meta_title, style: "display: block" %>
          <%= form.text_field :meta_title %>
        </div>

        <div>
          <%= form.label :meta_description, style: "display: block" %>
          <%= form.text_field :meta_description %>
        </div>

        <div>
          <%= form.label :headline, style: "display: block" %>
          <%= form.text_field :headline %>
        </div>

        <div>
          <%= form.label :incipit, style: "display: block" %>
          <%= form.text_field :incipit %>
        </div>

        <div class="field">
          <%= form.label :price %>
          <%#= form.text_field :price %>
          <%= form.number_field :price, step: :any %>
        </div>

        <div class="field">
          <p><%= image_tag eg_post.header_image.variant(resize_to_limit: [100, 100]) if eg_post.header_image.attached? %></p>
          <%= form.label :header_image %>
          <%= form.file_field :header_image %>
          <%= link_to 'Remove', delete_image_attachment_eg_post_path(eg_post.header_image.id), method: :get if eg_post.header_image.attached? %>
        </div>

        <div class="field">
          <%= form.label :content %>
          <%= form.rich_text_area :content %>
        </div>

        <div class="form-check">
          <%= form.label :published, class: "form-check-label" %>
          <%= form.check_box :published, class: "form-check-input" %>
          <%#= f.check_box :remove_logo, "data-size" => "medium", "data-on-color" => "primary", "data-on-text" => "SI", "data-off-color" => "default", "data-off-text" => "NO" %>
        </div>

        <div class="field">
          <%= form.label :published_at, class: "control-label" %>
          <%= form.text_field :published_at, class: "form-control" %>
        </div>

        <div>
          <%= form.label :user_id, style: "display: block" %>
          <%= form.text_field :user_id %>
        </div>

        <div>
          <%= form.submit %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/authors/eg_posts/edit.html.erb
<%# == Meta_data ============================================================ %>

<% provide(:html_head_title, t('eg_posts.edit.html_head_title', id: @eg_post.id)) %>

<%# == Meta_data - end ====================================================== %>

<h1>Editing eg post</h1>

<%= render 'form', eg_post: @eg_post, authors_url: authors_eg_post_url(@eg_post) %>

<br>

<div>
  <%= link_to "Show this eg post", @eg_post %> |
  <%= link_to "Back to authors eg posts", authors_eg_posts_path %>
</div>

app/views/authors/eg_posts/index.html.erb
<%# == Meta_data ============================================================ %>

<% provide(:html_head_title, "#{t 'eg_posts.index.html_head_title'}") %>

<%# == Meta_data - end ====================================================== %>

<p style="color: green"><%= notice %></p>

<h1>AUTHOR Eg posts</h1>

<div id="eg_posts">
  <% @eg_posts.each do |eg_post| %>
    <%= render eg_post %>
    <p>
      <%= link_to "Show this eg post", eg_post_path(eg_post) %>
    </p>
  <% end %>
</div>

<%= sanitize pagy_nav(@pagy) %>
<br/>
<br/>

<%= link_to "New eg post", new_authors_eg_post_path %>

app/views/authors/eg_posts/new.html.erb
<%# == Meta_data ============================================================ %>

<% provide(:html_head_title, t('eg_posts.new.html_head_title')) %>

<%# == Meta_data - end ====================================================== %>

<h1>New eg post</h1>

<%= render 'form', eg_post: @eg_post, authors_url: authors_eg_posts_url %>

<br>

<div>
  <%= link_to "Back to authors eg posts", authors_eg_posts_path %>
</div>