config/routes.rb
Rails.application.routes.draw do
  resources :preparatories
  resources :answers
  resources :lessons do
    resources :steps
  end

  namespace :authors do
    resources :eg_posts, :except => [:show] do
      member do
        delete :delete_image_attachment
      end
    end
  end
  resources :eg_posts, :only => [:index, :show] 

  resources :eg_users 
  get 'users/index'
  devise_for :users, path: '', path_names: {sign_in: 'login', sign_out: 'logout'}, controllers: { sessions: 'users/sessions' }
  resources :users do
    member do
      get :delete_image_attachment
    end
  end

  get 'mockups/page_a'
  get 'mockups/page_b'
  get 'mockups/bs_grid'
  get 'mockups/bs_gutter'
  get 'mockups/bs_buttons'
  get 'mockups/bs_cards_and_panels'
  get 'mockups/bs_images'
  get 'mockups/bs_icons'
  get 'mockups/bs_theming_kit'
  get 'mockups/bs_ud_home'
  get 'mockups/bs_ud_news'
  get 'mockups/bs_ud_tema'
  get 'mockups/edu_index_4'
  get 'mockups/edu_course_detail_min'
  get 'mockups/ud_lessons_index'
  get 'mockups/ud_lessons_show'
  get 'mockups/ud_lessons_steps_show'
  get 'mockups/youtube_player'
  get 'mockups/stimulus_demo'
  #get 'eg_posts', to:'eg_posts#index', as: :user_root #creates user_root_path (default path after sign_in)
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'lessons#index'
end

app/models/eg_user.rb
class EgUser < ApplicationRecord
end

app/controllers/eg_users_controller.rb
class EgUsersController < ApplicationController
  before_action :set_eg_user, only: %i[ show edit update destroy ]

  # GET /eg_users or /eg_users.json
  def index
    @eg_users = EgUser.all
  end

  # GET /eg_users/1 or /eg_users/1.json
  def show
  end

  # GET /eg_users/new
  def new
    @eg_user = EgUser.new
  end

  # GET /eg_users/1/edit
  def edit
  end

  # POST /eg_users or /eg_users.json
  def create
    @eg_user = EgUser.new(eg_user_params)

    respond_to do |format|
      if @eg_user.save
        format.html { redirect_to eg_user_url(@eg_user), notice: "Eg user was successfully created." }
        format.json { render :show, status: :created, location: @eg_user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @eg_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /eg_users/1 or /eg_users/1.json
  def update
    respond_to do |format|
      if @eg_user.update(eg_user_params)
        format.html { redirect_to eg_user_url(@eg_user), notice: "Eg user was successfully updated." }
        format.json { render :show, status: :ok, location: @eg_user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @eg_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /eg_users/1 or /eg_users/1.json
  def destroy
    @eg_user.destroy

    respond_to do |format|
      format.html { redirect_to eg_users_url, notice: "Eg user was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_eg_user
      @eg_user = EgUser.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def eg_user_params
      params.require(:eg_user).permit(:name, :email, :encrypted_password)
    end
end

app/helpers/eg_users_helper.rb
module EgUsersHelper
end

app/views/eg_users/_eg_user.html.erb
<div id="<%= dom_id eg_user %>">
  <p>
    <strong>Name:</strong>
    <%= eg_user.name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= eg_user.email %>
  </p>

  <p>
    <strong>Encrypted password:</strong>
    <%= eg_user.encrypted_password %>
  </p>

</div>

app/views/eg_users/_form.html.erb
<%= form_with(model: eg_user) do |form| %>
  <% if eg_user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(eg_user.errors.count, "error") %> prohibited this eg_user from being saved:</h2>

      <ul>
        <% eg_user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :encrypted_password, style: "display: block" %>
    <%= form.text_field :encrypted_password %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/eg_users/edit.html.erb
<h1>Editing eg user</h1>

<%= render "form", eg_user: @eg_user %>

<br>

<div>
  <%= link_to "Show this eg user", @eg_user %> |
  <%= link_to "Back to eg users", eg_users_path %>
</div>

app/views/eg_users/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Eg users</h1>

<div id="eg_users">
  <% @eg_users.each do |eg_user| %>
    <%= render eg_user %>
    <p>
      <%= link_to "Show this eg user", eg_user %>
    </p>
  <% end %>
</div>

<%= link_to "New eg user", new_eg_user_path %>

app/views/eg_users/new.html.erb
<h1>New eg user</h1>

<%= render "form", eg_user: @eg_user %>

<br>

<div>
  <%= link_to "Back to eg users", eg_users_path %>
</div>

app/views/eg_users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @eg_user %>

<div>
  <%= link_to "Edit this eg user", edit_eg_user_path(@eg_user) %> |
  <%= link_to "Back to eg users", eg_users_path %>

  <%= button_to "Destroy this eg user", @eg_user, method: :delete %>
</div>