config/routes.rb
Rails.application.routes.draw do
  resources :preparatories
  resources :answers
  resources :lessons do
    resources :steps
  end

  namespace :authors do
    resources :eg_posts, :except => [:show] do
      member do
        delete :delete_image_attachment
      end
    end
  end
  resources :eg_posts, :only => [:index, :show] 

  resources :eg_users 
  get 'users/index'
  devise_for :users, path: '', path_names: {sign_in: 'login', sign_out: 'logout'}, controllers: { sessions: 'users/sessions' }
  resources :users do
    member do
      get :delete_image_attachment
    end
  end

  get 'mockups/page_a'
  get 'mockups/page_b'
  get 'mockups/bs_grid'
  get 'mockups/bs_gutter'
  get 'mockups/bs_buttons'
  get 'mockups/bs_cards_and_panels'
  get 'mockups/bs_images'
  get 'mockups/bs_icons'
  get 'mockups/bs_theming_kit'
  get 'mockups/bs_ud_home'
  get 'mockups/bs_ud_news'
  get 'mockups/bs_ud_tema'
  get 'mockups/edu_index_4'
  get 'mockups/edu_course_detail_min'
  get 'mockups/ud_lessons_index'
  get 'mockups/ud_lessons_show'
  get 'mockups/ud_lessons_steps_show'
  get 'mockups/youtube_player'
  get 'mockups/stimulus_demo'
  #get 'eg_posts', to:'eg_posts#index', as: :user_root #creates user_root_path (default path after sign_in)
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'lessons#index'
end

app/models/user.rb
class User < ApplicationRecord
  # == Constants ============================================================
  
  # == Extensions ===========================================================

  ## devise
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :registerable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable

  # == Attributes ===========================================================

  ## enum
  #enum language: [:it, :en]
  enum language: {it: 0, en: 1}
  #enum role: [:user, :admin, :moderator, :author]
  enum role: {user: 0, admin: 1, moderator:2, author:3}

  ## ActiveStorage
  has_one_attached :profile_image

  # == Relationships ========================================================

  ## association one-to-many
  has_many :eg_posts
  has_many :answers

  # == Validations ==========================================================

  # == Scopes ===============================================================

  # == Callbacks ============================================================

  # == Class Methods ========================================================

  # == Instance Methods =====================================================
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  layout 'entrance'

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  #before_action :set_user, only: %i[ show edit update destroy ]
 
  # GET /users or /users.json
  def index
    #@users = User.all
    @pagy, @users = pagy(User.all.order(created_at: "DESC"), items: 3)
    authorize @users
  end

  # GET /users/1 or /eg_users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
    authorize @user
  end
  
  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)
    authorize @user

    respond_to do |format|
      if @user.save
        #format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.html { redirect_to user_url(@user), notice: t(".notice") } # notice: "User was successfully created."
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        #format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.html { redirect_to user_url(@user), notice: t(".notice") } # notice: "User was successfully updated."
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy unless @user == current_user
    respond_to do |format|
      format.html do
        #redirect_to users_url, notice: "User was successfully destroyed." unless @user == current_user
        #redirect_to users_url, notice: "The logged in user cannot be destroyed." if @user == current_user
        redirect_to users_url, notice: t(".notice") unless @user == current_user # notice: "User was successfully destroyed."
        redirect_to users_url, notice: t(".notice_logged_in") if @user == current_user #  notice: "The logged in user cannot be destroyed."
      end
      format.json { head :no_content }
    end
  end

  def delete_image_attachment
    @image_to_delete = ActiveStorage::Attachment.find(params[:id])
    @image_to_delete.purge
    redirect_back(fallback_location: request.referer)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
      authorize @user
    end

    # Only allow a list of trusted parameters through.
    def user_params
      if params[:user][:password].blank?
        params.require(:user).permit(:username, :email, :language, :role, :profile_image, :first_name, :last_name, :location, :bio, :phone_number)
      else
        params.require(:user).permit(:username, :email, :password, :password_confirmation, :language, :role, :profile_image, :first_name, :last_name, :location, :bio, :phone_number)
      end
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<!-- Form -->
<%= form_with(model: user, class: "row g-4") do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <!-- Profile picture -->
  <div class="col-12 justify-content-center align-items-center">
    <% if user.profile_image.attached? %>

      <%= form.label :profile_image, class: "form-label" %>
      <div class="d-flex align-items-center">
        <label class="position-relative me-4" for="uploadfile-1" title="Replace this pic">
          <!-- Avatar place holder -->
          <span class="avatar avatar-xl">
            <%= image_tag user.profile_image.variant(resize_to_fit: [100, 100]), id: "uploadfile-1-preview", class: "avatar-img rounded-circle border border-white border-3 shadow", alt: "" %>
          </span>
          <!-- Remove btn -->
          <%= link_to delete_image_attachment_user_path(user.profile_image.id), class: "uploadremove" do %>
            <i class="bi bi-x text-white"></i>
          <% end %>
        </label>
        <!-- Upload button -->
        <label class="btn btn-primary-soft mb-0" for="uploadfile-fla">Scegli nuova immagine (sarà applicata su Aggiorna utente)</label>
        <%= form.file_field :profile_image, id: "uploadfile-fla", style: "visibility:hidden;" %>
      </div>
    <% else %>
        <p>Nessuna immagine presente</p>
        <!-- Avatar place holder -->
        <span class="avatar avatar-xl">
          <%= image_tag "edu/avatar/07.jpg", id: "uploadfile-1-preview", class: "avatar-img rounded-circle border border-white border-3 shadow", alt:"" %>
        </span>

        <!-- Upload button -->
        <label class="btn btn-primary-soft mb-0" for="uploadfile-fla">Scegli nuova immagine (sarà applicata su Aggiorna utente)</label>
        <%#= form.file_field :profile_image, class: "form-control d-none" %>
        <%= form.file_field :profile_image, id: "uploadfile-fla", style: "visibility:hidden;" %>
    <% end %>
  </div>


  <!-- Full name -->
  <div class="col-12">
    <label class="form-label">Full name</label>
    <%#= form.label :name, style: "display: block" %>
    <div class="input-group">
      <!--<input type="text" class="form-control" value="Lori" placeholder="First name">-->
      <!--<input type="text" class="form-control" value="Stevens" placeholder="Last name">-->
      <%= form.text_field :first_name, placeholder: true, class: "form-control" %>
      <%= form.text_field :last_name, placeholder: true, class: "form-control" %>
    </div>
  </div>

  <!-- Username -->
  <div class="col-md-6">
    <!--<label class="form-label">Username</label>-->
    <%= form.label :username, class: "form-label" %>
    <div class="input-group">
      <span class="input-group-text">Ubuntudream.com</span>
      <!--<input type="text" class="form-control" value="loristev">-->
      <%= form.text_field :username, placeholder: true, class: "form-control" %>
    </div>
  </div>

  <!-- Email id -->
  <div class="col-md-6">
    <%= form.label :email, class: "form-label" %>
    <%= form.text_field :email, placeholder: true, class: "form-control" %>
  </div>

  <!-- Phone number -->
  <div class="col-md-6">
    <%= form.label :phone_number, class: "form-label" %>
    <%= form.text_field :phone_number, placeholder: true, class: "form-control" %>
  </div>

  <!-- Location -->
  <div class="col-md-6">
    <%= form.label :location, class: "form-label" %>
    <%= form.text_field :location, placeholder: true, class: "form-control" %>
  </div>
  
  <!-- About me -->
  <div class="col-12">
    <!--<label class="form-label">About me</label>-->
    <!--<textarea class="form-control" rows="3">I’ve found a way to get paid for my favorite hobby, and do so while following my dream of traveling the world.</textarea>-->
    <%= form.label :bio, class: "form-label" %>
    <%= form.text_area :bio, placeholder: true, class: "form-control", row: "3" %>
    <div class="form-text">Brief description for your profile.</div> 
  </div>


  <!-- Password -->
  <div class="col-md-6">
    <%= form.label :password, class: "form-label" %>
    <%= form.text_field :password, placeholder: true, class: "form-control" %>
  </div>


  <!-- Password Confirmation -->
  <div class="col-md-6">
    <%= form.label :password_confirmation, class: "form-label" %>
    <%= form.text_field :password_confirmation, placeholder: true, class: "form-control" %>
  </div>

  <!-- Language -->
  <div class="col-md-6">
    <%= form.label :language, class: "form-label" %>
    <%#= form.text_field :language, placeholder: true, class: "form-control" %>
    <%#= form.text_field :language %>
    <%#= form.select(:language, [["Lingua Italiana", "it"], ["Lingua Inglese", "en"]]) %>
    <%= form.select(:language, User.languages.keys.map {|language| [language,language]},{}, class: "form-select") %>
    <%#= form.select(:language, User.languages.keys.map {|language| [language.titleize,language]}) %>
  </div>


  <%# if user_signed_in? and current_user.admin? %>
  <% if current_user.present? and current_user.admin? and @user != current_user %>
    <div>
      <%= form.label :role %>
      <%#= form.select(:role, User.roles.keys.map {|role| [role.titleize,role]}) %>
      <%= form.select(:role, User.roles.keys.map {|role| [User.human_attribute_name("role.#{role}"), role]}) %>
      <%#= form.collection_radio_buttons :role, Hash[User.roles.map { |k,v| [k, User.human_attribute_name("role.#{k}")] }], :first, :second %>
    </div>
  <% end %>

  
  <%#= form.label :encrypted_password, style: "display: block" %>
  <%#= form.text_field :encrypted_password %>
  
  <!-- Save button -->
  <div class="d-sm-flex justify-content-end">
    <!--<button type="button" class="btn btn-primary mb-0">Save changes</button>-->
    <%= form.submit class: "btn btn-primary mb-0" %>
  </div>

<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">

  <!-- =======================
  Page content START -->
  <section class="pt-5 pb-0">
    <div class="container">
      <div class="row g-0 g-lg-5">

        <!-- Left sidebar START -->
        <div class="col-lg-4">
          <div class="row">
            <div class="col-md-6 col-lg-12">
              <!-- Instructor image START -->
              <div class="card shadow p-2 mb-4 text-center">
                <div class="rounded-3">
                  <!-- Image -->
                  <%# <img src="assets/images/instructor/07.jpg" class="card-img" alt="course image"> %>
                  <% if user.profile_image.attached? %>
                    <%#= image_tag user.profile_image.variant(resize_to_limit: [100, 100]).processed.url %>
                    <%#= image_tag user.profile_image.variant(resize_to_limit: [150, 150]) %>
                    <%#= image_tag user.profile_image %>
                    <%= image_tag user.profile_image.variant(resize_to_fit: [250, 250]).processed.url, class: "card-img", alt: "user image" %>
                  <% else %>
                    Nessuna immagine presente
                  <% end %>
                </div>
    
                <!-- Card body -->
                <div class="card-body px-3">
                    <%= link_to "Edit this user", edit_user_path(@user) %> |
                    <%= link_to "Back to users", users_path %>

                    <%= button_to "Destroy this user", @user, method: :delete unless @user == current_user %>
                </div>

              </div>
              <!-- Instructor image END -->
            </div>

          </div> <!-- Row End -->
        </div>
        <!-- Left sidebar END -->
          
        <!-- Main content START -->
        <div class="col-lg-8">
        
          <!-- Title -->
          <h5 class="mb-0">Hi, I am</h5>
          <h1 class="mb-0"><%= user.username %></h1>
          <p>Graphic Designer</p>
          <!-- Content -->
          <p class="mt-4"><%= user.bio %></p>
          <!-- Personal info -->
          <ul class="list-group list-group-borderless">
            <li class="list-group-item px-0">
              <span class="h6 fw-light"><i class="fas fa-fw fa-map-marker-alt text-primary me-1 me-sm-3"></i>Role:</span>
              <span><%= user.role %></span>
            </li>
            <li class="list-group-item px-0">
              <span class="h6 fw-light"><i class="fas fa-fw fa-envelope text-primary me-1 me-sm-3"></i>Email:</span>
              <span><%= user.email %></span>
            </li>
            <li class="list-group-item px-0">
              <span class="h6 fw-light"><i class="fas fa-fw fa-headphones text-primary me-1 me-sm-3"></i>Phone number:</span>
              <span>+896-789-546</span>
            </li>
            <li class="list-group-item px-0">
              <span class="h6 fw-light"><i class="fas fa-fw fa-globe text-primary me-1 me-sm-3"></i>Lingua:</span>
              <span><%= user.language %></span>
            </li>
          </ul>

        </div>
        <!-- Main content END -->

      </div><!-- Row END -->
    </div>
  </section>
  <!-- =======================
  Page content END -->

</div> <!-- end Rails dom_id user (usefull for hotwire) -->

app/views/users/edit.html.erb
<%# == Meta_data ============================================================ %>

<% provide(:html_head_title, "#{t 'users.edit.html_head_title'} #{@user.username}") %>

<%# == Meta_data - end ====================================================== %>

<!-- **************** MAIN CONTENT START **************** -->
<main>
	
<!-- =======================
Page Banner START -->
<section class="pt-0">
	<!-- Main banner background image -->
	<div class="container-fluid px-0">
		<!--<div class="bg-blue h-100px h-md-200px rounded-0" style="background:url(assets/images/pattern/04.png) no-repeat center center; background-size:cover;">-->
		<div class="bg-blue h-100px h-md-200px rounded-0" style="background:url(<%= image_path('edu/pattern/04.png') %>) no-repeat center center; background-size:cover;">
		</div>
	</div>
	<div class="container mt-n4">
		<div class="row">
			<!-- Profile banner START -->
			<div class="col-12">
				<div class="card bg-transparent card-body p-0">
					<div class="row d-flex justify-content-between">
						<!-- Avatar -->
						<div class="col-auto mt-4 mt-md-0">
							<div class="avatar avatar-xxl mt-n3">
								<!--<img class="avatar-img rounded-circle border border-white border-3 shadow" src="assets/images/avatar/01.jpg" alt="">-->
								<%#= image_tag "edu/avatar/01.jpg", class: "avatar-img rounded-circle border border-white border-3 shadow", alt: "" %>
								<%= image_tag @user.profile_image, class: "avatar-img rounded-circle border border-white border-3 shadow", alt: "" %>
								<%#= image_tag @user.profile_image.variant(resize_to_fit: [100, 100]).processed.url %>
							</div>
						</div>
						<!-- Profile info -->
						<div class="col d-md-flex justify-content-between align-items-center mt-4">
							<div>
								<h1 class="my-1 fs-4"><%= @user.username %> <i class="bi bi-patch-check-fill text-info small"></i></h1>
								<ul class="list-inline mb-0">
									<li class="list-inline-item h6 fw-light me-3 mb-1 mb-sm-0"><i class="fas fa-star text-warning me-2"></i>4.5/5.0</li>
									<li class="list-inline-item h6 fw-light me-3 mb-1 mb-sm-0"><i class="fas fa-user-graduate text-orange me-2"></i>12k Enrolled Students</li>
									<li class="list-inline-item h6 fw-light me-3 mb-1 mb-sm-0"><i class="fas fa-book text-purple me-2"></i>25 Courses</li>
								</ul>
							</div>
						</div>
					</div>
				</div>
				<!-- Profile banner END -->
			</div>
		</div>
	</div>
</section>
<!-- =======================
Page Banner END -->

<!-- =======================
Page content START -->
<section class="pt-0">
	<div class="container">
		<div class="row">

			<!-- Main content START -->
			<div class="col-xl-9">
				<!-- Edit profile START -->
				<div class="card bg-transparent border rounded-3">
					<!-- Card header -->
					<div class="card-header bg-transparent border-bottom">
						<h3 class="card-header-title mb-0">Edit Profile</h3>
					</div>
					<!-- Card body START -->
					<div class="card-body">
						<!-- Form -->
						<%= render "form", user: @user %>
					</div>
					<!-- Card body END -->
				</div>
				<!-- Edit profile END -->

			</div>
			<!-- Main content END -->
		</div><!-- Row END -->
	</div>
</section>
<!-- =======================
Page content END -->

</main>
<!-- **************** MAIN CONTENT END **************** -->

<br>
<%#= render "form", user: @user %>
<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/index.html.erb
<%# == Meta_data ============================================================ %>

<% provide(:html_head_title, "#{t 'users.index.html_head_title'}") %>

<%# == Meta_data - end ====================================================== %>

<p style="color: green"><%= notice %></p>

<h1>Users</h1>

<div id="users">
  <% @users.each do |user| %>
    <%= render user %>
    <p>
      <%= link_to "Show this user", user %>
    </p>
  <% end %>
</div>

<%= sanitize pagy_nav(@pagy) %>
<br/>
<br/>

<%= link_to "New user", new_user_path %>

app/views/users/new.html.erb
<%# == Meta_data ============================================================ %>

<% provide(:html_head_title, "#{t 'users.new.html_head_title'}") %>

<%# == Meta_data - end ====================================================== %>

<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/show.html.erb
<%# == Meta_data ============================================================ %>

<% provide(:html_head_title, @user.username) %>

<%# == Meta_data - end ====================================================== %>

<p style="color: green"><%= notice %></p>

<%= render @user %>

  <%#= link_to "Edit this user", edit_user_path(@user) %> |
  <%#= link_to "Back to users", users_path %>
  <%#= button_to "Destroy this user", @user, method: :delete unless @user == current_user %>